plugins/modules/podman_image.py

with force: true, podman_image would always report changed regardless
of whether or not the pull or build operation resulted in a new image.
With this commit, check the image digest before and after and only
reported changed if the digest is different.
I'm relocating this from https://github.com/ansible/ansible/pull/68542

podman_image: only set changed=true if there is a new image

---

plugins/modules/podman_image.py

podman_image module uses 'podman push' command with wrong
flag '--remove_signatures' instead of '--remove-signatures'
This patch fixes the given typo.
Fixes: ansible/ansible#67965
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
- Bugfix Pull Request
plugins/modules/podman_image.py

podman_image: use correct option for remove_signatures flag

---

plugins/connection/podman.py

Fixes #29 
Sometimes container fails to copy in rootless mode and the message is different, so try to set pause=false w/o depending on the error string.

Run pause=false w/o message condition

---

.github/workflows/connections_tests.yml
plugins/connection/buildah.py

Support rootless containers with buildah connection
Fixes https://github.com/ansible/ansible/issues/63316

Buildah connection rootless

---

plugins/modules/podman_container.py

Partially solves issues from #21, #31 
Fixes #20 
`workdir` and `volumes` can be set in the image, so for better idempotency we'll need to inspect image. For now ignore these settings if they're not set.

Fix idempotency issues with workdir and volumes

---

plugins/modules/podman_container.py
tests/integration/targets/podman_container/tasks/main.yml

Consider pod container differences, they change utc, network, ipc according to their pods.
Add different default for cpu_shares on podman 1.8.* versions
Add test for containers idempotency in pods
Partially solves #21 and #31

Improve idempotency of podman_container

---

plugins/modules/podman_container.py

user and stop signal can be defined in images, ignore them if they're not set
Fixes #31 and partially solved #21

Add idempotency for user and stop signal

---

plugins/connection/podman.py

Workaround for issue https://github.com/containers/libpod/issues/6856
When podman runs with CGroups v2 and rootless container,
it mounts directory without error, but mounted directory is empty.
Add check for the directory if it's empty.
Fix #70 
Let's revert it when podman will be fixed, see issue https://github.com/containers/libpod/issues/6856

Add check for empty dir for podman connection mount

---

plugins/connection/podman.py

Move these messages to level 4 not to bother people, eventually
this is a usual case for rootless.
Fix #73

Increase verbosity for mount failure messages

---

plugins/modules/podman_container.py
tests/integration/targets/podman_container_idempotency/tasks/idem_volumes.yml

In case of trailing slash or double slashes, the Podman strips it
automatically. Prepare input data accordingly, so we can compare
with Podman inspected one.
Fix #77

Improve idempotency for volumes with slashes

---

plugins/connection/podman.py

Commit cc8d4bb4510bcc79537ed3fa591fb9cace576ae9 changed `_podman()` to accept a string or a list for the "cmd" parameter. Update the docstring for this parameter to reflect this.

doc: _podman() cmd value can be a list

---

plugins/connection/podman.py

In podman connection when we copy file to container and work as
non-root user, need to set correct ownership for the files.
Since ansible change https://github.com/ansible/ansible/pull/70221
it's broken, because of new permissions ansible set to copied files.

Chown file for users when copy them to container

---

plugins/modules/podman_container.py

If init: true/yes is set it passed as string argument and produces error.
Default init path is predefined as /dev/init and automically injected from catatonit package https://github.com/openSUSE/catatonit
Custom can be set with --init-path=

Fix init: option it's boolean not string

---

plugins/modules/podman_network.py
tests/integration/targets/podman_network/tasks/main.yml

If dnsname plugins is not in specified set of paths, it's not
installed. If it's not installed, then the default values of
disable-dns will be True (as dns is disabled).
Fix #112

Check if dnsname plugin installed for CNI

---

plugins/modules/podman_volume.py
tests/integration/targets/podman_volume/tasks/main.yml

Options can be set multiple times for a driver, so let's configure
them as a list.
Fix idempotency for options and add tests for them.
Fix #108

Set options for a volume as list and fix idempotency

---

plugins/modules/podman_container.py
tests/integration/targets/podman_container_idempotency/files/Dockerfile

In #113 we made a change to lowercase only keys, so signals should
be now upper case.
Related to #125.

Fix signals case for podman_container

---

.github/workflows/podman_logout.yml
ci/playbooks/containers/podman_logout.yml
plugins/modules/podman_logout.py
tests/integration/targets/podman_logout/tasks/main.yml

This adds a module to log out of a specified container registry or all registries wrapping the `podman logout` command with all its options.
I've also added a few tests, which are possible without an actual log in. The GitHub Actions workflow as well as the playbook are adjusted copies of the podman_volume_info equivalent.
Please let me know if you have any suggestions. Once login and login_info modules are in place, a combination of them can be tested together (if secrets are added to this repository).
Labelling this PR for hacktoberfest would be appreciated.
Addresses #94

Add podman logout module

---

.github/workflows/podman_login_info.yml
ci/playbooks/containers/podman_login_info.yml
plugins/modules/podman_login_info.py
tests/integration/targets/podman_login_info/tasks/main.yml

This adds a module to check if one is logged in to a given container registry wrapping the `podman login --get-login` command with all its options.
I've also added a few tests, which are possible without an actual log in. The GitHub Actions workflow as well as the playbook are adjusted copies of the `podman_volume_info` equivalent.
I'd be willing to also look into creating `podman_login` and `podman_logout` modules as listed in #93 and #94 since they'd be useful for a project of mine.
Please let me know if you have any suggestions.
Labelling this PR for hacktoberfest would be appreciated.

Add podman_login_info module

---

plugins/modules/podman_network.py

the IP range must be in CIDR notation not IP1-IP2, at least according to man page
of podman-network-create

Correct IP range example for podman_network

---

plugins/modules/podman_network.py
tests/integration/targets/podman_network/tasks/main.yml

Fix #147 
Add network options like MTU, VLAN, IPv6

Add ipv6. mtu, vlan to network and fix CI

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py
tests/integration/targets/podman_container/tasks/main.yml
tests/integration/targets/podman_containers/tasks/main.yml

Add state 'created' which will ensure container exists in current
configuration. It can either run or not.
Fix #165

Add 'created' state for podman_container

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py
tests/integration/targets/podman_container/tasks/main.yml

Don't require an image when restarting container, only the
container name.
Fix #161

Restart container in a simple manner

---

plugins/module_utils/podman/podman_container_lib.py

Preserve case sensitivity in the command param's idempotency check by:
- using shlex to split command line strings (`shlex.split`:"Split the string s using shell-like syntax.")
- removing the use of `lower()` in both cases of string or list
fixes #173

podman_container_lib: fix command param idempotency

---

plugins/module_utils/podman/podman_container_lib.py

This change fixes containers always being rebuilt when the `cap_add` or `cap_drop` options are used. For example:
```yaml
containers.podman.podman_container:
cap_add:
- "NET_BIND_SERVICE"
- "CAP_AUDIT_WRITE"
...
```
Consecutive runs produce the following diff:
```
--- before
+++ after
@@ -1 +1 @@
-cap_add - ['CAP_AUDIT_WRITE', 'CAP_NET_BIND_SERVICE']
+cap_add - ['CAP_AUDIT_WRITE', 'CAP_NET_BIND_SERVICE', 'cap_cap_audit_write', 'cap_net_bind_service']
```
Lower-casing and checking if the option already contains the `cap_` prefix fixes the issue (for me).

Fix 'cap_add' and 'cap_drop' idempotency

---

plugins/module_utils/podman/podman_container_lib.py

Fixes the following error when using this module with a systemd-enabled container:
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'sigrtmin+3'
failed: [XXX] (item=9) => {"ansible_loop_var": "item", "changed": false, "item": 9, "module_stderr": "Shared connection to XXX closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1615576591.0259745-488102-124656477496642/AnsiballZ_podman_container.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1615576591.0259745-488102-124656477496642/AnsiballZ_podman_container.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File …

Add sigrtmin+3 signal (required for systemd containers)

---

plugins/module_utils/podman/podman_pod_lib.py
tests/integration/targets/podman_pod/tasks/main.yml

Stop pod without recreating if its definition isn't the same as
before.
Fix #215

Stop pods without recreating them

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container_idempotency/tasks/idem_labels.yml

When we lower cases for all keys, but leave it original case for
all values, we need to do the same with input labels.
Add test.
Fix #227

Fix uppercase labels idempotency issue

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_containers.py
tests/integration/targets/podman_containers/tasks/main.yml
tests/integration/targets/podman_containers/tasks/root-multi.yml

Options in multiple podman containers module are broken when they're lists or booleans. Ansible creates a list from a single option if it's defined as a list in args. Do the same, and convert option to the required type if need.

Fix multi-containers options

---

plugins/module_utils/podman/podman_container_lib.py

Because of podman bug we can't discover what's --no-hosts option
set to.

Disable no-hosts idempotency

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py
tests/integration/targets/podman_container/tasks/main.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_all.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_labels.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_networks.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_ports.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_stopsignal.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_users.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_volumes.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_workdir.yml
tests/integration/targets/podman_container_idempotency/tasks/root-podman.yml
tests/integration/targets/podman_container_idempotency/tasks/rootless-podman-network.yml
tests/integration/targets/podman_containers/tasks/main.yml

For being more compliant with docker module change "present" state to be "created".
Make actions "start", "restart", "stop" available for containers without full definition.
Fix #257 
Fix #247

Change present state to be as created state

---

plugins/module_utils/podman/podman_container_lib.py

Fix #276
Label 'podman_systemd_unit' is the marker for container starting
from systemd generated file. In this case:
* Ignore podman_systemd_unit label
* Ignore cidfile settings when this label presents

Fix idempotency with systemd podman files

---

plugins/modules/podman_volume.py

Fix #282
Remove UID and GID from podman volume options.
We don't support idempotency for them due to conflicting changes
in podman versions.

Remove idempotency leftovers of volumes GID,UID 

---

plugins/modules/podman_container.py
plugins/modules/podman_pod.py

As of this line https://github.com/containers/ansible-podman-collections/blob/5b3f8a4d3dee5031bd639965539158ce273e9f84/plugins/module_utils/podman/common.py#L66 it should be "path", not "file"

Fix suboption key in podman_container -> generate_systemd documentation

---

plugins/modules/podman_secret.py
tests/integration/targets/podman_secret/tasks/main.yml

This solves issue https://github.com/containers/ansible-podman-collections/issues/330 , which describes how podman_secret adds newlines (\n) to secrets.
After having a look at the [source code](https://github.com/containers/ansible-podman-collections/blob/a0377fbd240f39d35c8b833b1f961c61b445fc1b/plugins/modules/podman_secret.py#L99) and the [run_command documentation](https://docs.ansible.com/ansible/latest/reference_appendices/module_utils.html#ansible-module-utils), it seems the parameter binary_data of run_command must be `true` to prevent new lines being added to data:
> Kw binary_data - If False, append a newline to the data. Default False

Don't add newlines to secrets

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py
tests/integration/targets/podman_container/tasks/main.yml

Like "volume", "mount" can be passed multiple times to the container
creation/run, therefore we want to support a list of string, and a
"mounts" alias.

Allow to actually pass a list of string for "mounts"

---

plugins/module_utils/podman/common.py
plugins/modules/podman_container.py

Fixes #318.
Currently it's set independently from `remove`.

Support --new in generate_systemd

---

plugins/modules/podman_container.py
plugins/modules/podman_pod.py

Add --new options in generate_systemd option documentation for podman_pod. Also fixes #335

Add documentations for generate_systemd

---

plugins/module_utils/podman/podman_container_lib.py

The default value of log-driver is not defined now and can change
depending on the platform.

Remove default value of log-driver

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py

The --read-only option is not checked for changes between runs of
ansible thus the container is not recreated if the user changes
the root image between read-write to read-only.
Default for the read_only variable set to False in line with
documentation and so that later checks are simplified.
This is a fix for bug #383.
Signed-off-by: Andrew <rubiksdot@grue.cc>

fix check for read-only change of root image

---

plugins/modules/podman_pod.py

to avoid them being intrepreted as scalars. #394

Podman Pod: Update examples to use quotes when publishing ports

---

plugins/modules/podman_load.py
tests/integration/targets/podman_load/tasks/main.yml

Fix #411 
Loop over image names when multiple images present in archive
Appropriately appending output
Signed-off-by: Cory Prelerson <cprelerson42@gmail.com>

Loop over image names when multiple images present in archive

---

plugins/modules/podman_network.py

Remove logic with internal and dns, since Podman supports it in
recent versions.
Fix #350

Fix internal networks idempotency

---

plugins/modules/podman_play.py

Was passing a file handle instead of a string.
Closes #415.

Fix play_kube not working when yaml not installed on target (#415)

---

plugins/modules/podman_container.py

I believe "prefix" is what was meant here

podman_container.py: Fix typo in the documentation

---

plugins/modules/podman_image.py
tests/integration/targets/podman_image/tasks/main.yml

Update `podman_image` to remove image with image id

---

plugins/modules/podman_network.py
tests/integration/targets/podman_network/tasks/main.yml

Before that it didn't work when only one option set.
Fix #433

Allow specify podman_network options MTU and VLAN separately

---

plugins/connection/podman.py

For completeness sake (and because I looked for it and did not find
it), this adds a docstring line for the "use_container_id" parameter.
Signed-off-by: Cleber Rosa <crosa@redhat.com>

Add missing docstring for method that executes the podman commands

---

plugins/connection/podman.py
plugins/module_utils/podman/common.py
plugins/module_utils/podman/podman_container_lib.py
plugins/module_utils/podman/podman_pod_lib.py
plugins/modules/podman_network.py
plugins/modules/podman_volume.py

Fix #422
The distutils package is deprecated and slated for removal in Python 3.12

Remove distutils as deprecated

---

plugins/module_utils/podman/podman_container_lib.py

podman 4.1.x has changed the ipc namespace mode default to
shareable[1] that results in containers being restarted.
[1] https://github.com/containers/podman/commit/3987c529f473178c51feb69d5252c7d5c2a8f697
Resolves: rhbz#2101495

Change IpcMode default to shareable

---

tests/integration/targets/podman_container_idempotency/tasks/build_test_container.yml

Probably we hit a bug in CI:
https://github.com/containers/buildah/issues/3887
Unset envs to prevent error "sd-bus call: Transport endpoint is not connected"

Fix building image with buildah and become in CI

---

plugins/module_utils/podman/podman_container_lib.py

This fixes Issue #345 by making two changes:
1. If `generate_systemd.new` is set then `rm` is automatically set. This is needed because containers started by systemd services generated with the `--new` option always start with --rm. Otherwise ansible will try to restart container on every rerun, as ansible thinks `rm` should be off, while it has been turned on by the systemd service.
I also tried only changing `PodmanContainerDiff` for this, but that runs into the problem that then the container starts without `rm` when started by ansible but with `rm` once it has been restarted using systemd, leading to further problems.
2. Don't try to delete containers with `AutoRemove` set. As the containers are already removed by podman when they are stopped ansible will fail when it tries to remove …

Fix rerunning playbooks with generate_systemd --new

---

plugins/modules/podman_play.py

The `podman_play` example doesn't work because a required argument is missing.

Add required argument to example

---

plugins/module_utils/podman/podman_pod_lib.py

Older podman versions, such as podman 1.6.4 on CentOS 7, do not have the pod status in the 'podman pod inspect' output. Added an attribute and a method to PodmanPod to fetch the 'podman pod ps' output. Added an additional status check to the exising running property that uses the 'ps' info.
Fixes #499
Signed-off-by: antonc42 <antonc42@users.noreply.github.com>

fix pod running status for older podman versions

---

.github/workflows/podman_generate_systemd.yml
ci/playbooks/containers/podman_generate_systemd.yml
plugins/modules/podman_generate_systemd.py
tests/integration/targets/podman_generate_systemd/tasks/main.yml

This pull request add a new module: `podman_generate_systemd`.
This module will generate systemd .service units for pods and containers.
In this Pull Request, I provide:
- The module code
- It's documentation
- An integration test
The module can be used to only generate the systemd .service units and
save them in an Ansible variable, or to create the unit files on the
host. It support the check mode.
If you specify a Pod, le unit for the pod and all its containers will
be generated.
The module support a lot of options:
- `name`: Name of the pod or container to export as systemd unit
- `dest`: Destination of the generated systemd unit file(s)
- `new`: Make the unit create the container before starting it
- `restart_policy`: Restart policy of the service
- `restart_sec`: Configures the time …

Podman generate systemd

---

plugins/become/podman_unshare.py

Signed-off-by: Janos Gerzson <gerzsonj@gmail.com>

[FIX] Issue #529: become plugin podman_unshare become_user default

---

plugins/connection/buildah.py

This fix is similar to the previous one from [#506](https://github.com/containers/ansible-podman-collections/pull/506), but in buildah.py connection plugin
Fix #541

fix for buildah improper remote target

---

.github/workflows/podman_prune.yml
ci/playbooks/containers/podman_prune.yml
plugins/modules/podman_prune.py
tests/integration/targets/podman_prune/tasks/main.yml

Added podman_prune module, it should fix https://github.com/containers/ansible-podman-collections/issues/352
WIP since i need to add some tests

added podman_prune module

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py

Fix #539
No idempotency for now, not clear how to detect it from config.

Add hooks-dir parameter for containers

---

plugins/modules/podman_generate_systemd.py

Improved documentation of `podman_generate_systemd` module.
The first commit fixes some typos. Most notably the command syntax is `systemctl daemon-reload` with a `-` in between. Furthermore I moved the hints regarding typical systemd unit folders to the description of the `dest` parameter, because that's where this info is needed.
The second commit changed an example because it took me some time to find out why my playbook crashed on the second run. It looked much like #345 and it turns out, while the `generate_systemd` part of the `container` module automatically adds `rm: true` when `new: true` is given, this behavior seems to be impossible for the new `podman_generate_systemd` module. On container creation it cannot know that the `podman_generate_systemd` module is used with `new: …

Improved documentation of `podman_generate_systemd` module

---

plugins/modules/podman_image.py

**Background**
During working on #563, I found some strange behaviors of `podman_image.find_image()` and `podman_image.inspect_image()`.
I guess this implementation is not as expected.
**Details**
These functions will execute `podman` commands such as `podman image ls <IMG_NAME> --format json` and `podman image inspect <IMG_NAME> --format json`.
The following snippet is from `find_image()`, and it looks `images` is expected to receive a list from `rc, images, err = self._run(args, ignore_errors=True) `. Then its length will be evaluated.
However, I believe that currently `images` is `str` type and it is `[]\n` if the target image doesn't exist on a server. So `len(image)` will be not zero, but 3 or more.
https://github.com/containers/ansible-podman-collections/blob/d5f7655464ed942a368e317f …

Convert str to json format before evaluating length in `find_image()` and `inspect_image()`.

---

plugins/modules/podman_image.py
tests/integration/targets/podman_image/tasks/main.yml

Update podman_image to specify CPU arch when pulling image

---

setup.py

https://github.com/pypa/setuptools/issues/3197
latest release of setuptools 61.0 broke pip install

CI: fix pip installation of the collection

---

plugins/modules/podman_play.py

This PR fixes the regex used when no `yaml` import is successful. When using the `recreate: true` option without `yaml` the error `Deployment doesn't have a name!` occured.

fix(podman-play): fix regex for pod kube recreate

---

plugins/module_utils/podman/podman_container_lib.py

Before this change, this task:
```yaml
- containers.podman.podman_container:
restart_policy: on-failure:3
```
always caused this diff:
```diff
--- before
+++ after
@@ -1 +1 @@
-restart_policy - on-failure
+restart_policy - on-failure:3
```

Fix idempotency for RestartPolicy when MaximumRetryCount > 0

---

plugins/module_utils/podman/podman_pod_lib.py
tests/integration/targets/podman_pod/tasks/main.yml

Previously, this would only mark the userns as expected when `uidmap` or `gidmap` is passed. However, in the case `userns` is passed, this is also expected to be set.

Fix idempotency checks when using `userns`

---

plugins/module_utils/podman/podman_container_lib.py

This reverts commit cb832c9a8487b9efa98d2e4ead491b6a5a3d0425. We lose flexibility in recreating workflow, replace actually does the same in Podman - stops and removes/creates.

Revert "Use replace option to recreate a container (#613)"

---

plugins/modules/podman_generate_systemd.py
tests/integration/targets/podman_generate_systemd/tasks/main.yml

Add a force field to podman_generate_systemd

---

plugins/modules/podman_runlabel.py

This is to implement the [podman container runlabel](https://docs.podman.io/en/latest/markdown/podman-container-runlabel.1.html) command.
* Related to feature request: #620

Add podman_runlabel module

---

.github/workflows/podman_container_exec.yml
ci/playbooks/containers/podman_container_exec.yml
plugins/modules/podman_container_exec.py
tests/integration/targets/podman_container_exec/tasks/main.yml

Add podman_container_exec module

---

plugins/module_utils/podman/podman_pod_lib.py
plugins/modules/podman_pod.py
tests/integration/targets/podman_pod/tasks/main.yml
tests/integration/targets/podman_pod/tasks/resource-limit.yml

Fixes #576 and add options to set resource limits.

Add options for resource limits to podman_pod

---

plugins/modules/podman_network.py

* Fixes #656 
* Remove `-f` flag when removing network with `podman network rm`, so that containers using the network won't be removed by default.
* Add `force` option (default False) to `podman_network`, which uses `-f` and removes containers using the network

Fix #656: Do not force network removal by default

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py

This adds the new parameter `healthcheck_failure_action`, which maps into the podman argument `--health-on-failure`. As explained in the [podman docs](https://docs.podman.io/en/latest/markdown/podman-run.1.html#health-on-failure-action):
> **--health-on-failure=action**
> Action to take once the container transitions to an unhealthy state. The default is none.
> 
> none: Take no action.
> 
> kill: Kill the container.
> 
> restart: Restart the container. Do not combine the restart action with the --restart flag. When running inside of a systemd unit, consider using the kill or stop action instead to make use of systemd’s restart policy.
> 
> stop: Stop the container.
> 
This argument is useful to be combined with the existing ones in the current …

Add support for health-on-failure action

---

plugins/modules/podman_play.py
tests/integration/targets/podman_play/tasks/files/play-pod.yaml
tests/integration/targets/podman_play/tasks/main.yml
tests/integration/targets/podman_play/tasks/play-options.yml
tests/integration/targets/podman_play/tasks/play-with-options.yml

Fixes #544 and added test. 
In addition, this change adds tests for PR https://github.com/containers/ansible-podman-collections/pull/577, which is also related to issue #544.

Add log_opt and annotaion options to podman_play module

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container/tasks/main.yml

Since SElinux labels are basically annotations[1], they are merged in a single comma separated string in the list by podman, so we need to split them in a sorted list if we want to compare it to the list that we provide to the module.
Also, a proper test for this case has been added.
[1] https://github.com/containers/podman/blob/d1236f46fc5cb29e8da296c3662f8ce869865030/libpod/define/annotations.go#L49-L54

Improve `security_opt` comparison between existing containers

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container/tasks/main.yml

If `recreate` flag is enabled we should be able to recreate stopped containers even if their configuration aren't changed.
This become important if those containers has bind mounted files that are recreated from scratch instead of being edited (for example files managed by ansible or puppet)

Recreate stopped containers if `recreate` flag is enabled

---

plugins/module_utils/podman/common.py

Fix #675
If we explicitly set to generate systemd with parameters, fail the module if the generation failed.

Fail if systemd generation failed and it's explicitly set

---

plugins/modules/podman_login.py

The second example in `podman_login.py` show the login for quay.io instead of the default registry.

Fix podman_login.py example name

---

plugins/module_utils/podman/common.py
plugins/modules/podman_secret.py
tests/integration/targets/podman_secret/tasks/main.yml

Add idempotency for podman_secret

---

plugins/modules/podman_network.py

This pull requests fixes a bug in the diff function (`diffparam_disable_dns`) for the parameter in the `podman_network` plugin (see #699).
It fixes the idempotency for `podman_network` when explicitly definining `disable_dns` parameter for Podman driver other than type `bridge`.
The problem was introduced in #650 (relating issue #647).

Fix idempotency for podman_network

---

plugins/module_utils/podman/common.py
plugins/module_utils/podman/podman_container_lib.py

We have a few calculations of given options and arguments from CreateCommand, so let's do it in a more convinient way. Define a function _createcommand which receives an argument and returns all values for it in a command line of Podman.

Add option to parse CreateCommand easily for diff calc

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py

I have updated the env_file parameter to use several file to set environment variables.
See https://github.com/containers/ansible-podman-collections/pull/694 for discussion history

Update env_file to accept a list of files instead of a single file

---

plugins/modules/podman_generate_systemd.py

Change the postgres_local example to use the scope of "user" so the unit file saved to ~/.config/systemd/user/ will be used by systemd.

Fix broken example for podman_generate_systemd

---

plugins/module_utils/podman/podman_pod_lib.py

Fixes #712
Podman 5 changed the output of `podman pod info` (when run on a single pod) from being a dict to being a list of dicts:
https://github.com/containers/podman/pull/21514
this should handle both ways. Unfortunately not sure how to add a test for this as I can't see a unit test that mocks the output of the command, only the integration test that gets real live output, and I'm not sure how to get that test run with Podman 5.

podman pod info: handle return being list in Podman 5

---

plugins/modules/podman_play.py
tests/integration/targets/podman_play/tasks/main.yml

As discussed [here](https://github.com/containers/ansible-podman-collections/pull/724#discussion_r1535719450), this PR improves the logic for deleting pods/containers in podman_play, more specifically updates`remove_associated_pods` and uses `podman kube play --down` instead.

Update the logic for deleting pods/containers in podman_play

---

plugins/modules/podman_pod_info.py

Do not try to deserialize json when out is empty
Fixes #731

Fix pod info for non-existant pods

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container_idempotency/tasks/idem_volumes.yml

Add idempotency for mounts and volumes

---

plugins/module_utils/podman/quadlet.py

Align the keys in the NetworkQuadlet param_map to match the keys in the documentation.

Fix missing entries in network quadlet generated file (#792)

---

.github/workflows/podman_container_copy.yml
ci/playbooks/containers/podman_container_copy.yml
plugins/modules/podman_container_copy.py
tests/integration/targets/podman_container_copy/tasks/main.yml

As the title suggests, this PR covers a draft proposal of a module for podman cp command.
It basically reflects the podman cp usage, allowing host -> container copy (default) or container -> host (configurable via a parameter).
Attached are also the tests for both flows (host->container, container->host)

Proposal: add podman_container_copy module

---

plugins/module_utils/podman/podman_container_lib.py

"--health-startup-command" is a wrong parameter.
the correct syntax is
"--health-startup-cmd"

Fix health-startup-cmd

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container/tasks/main.yml

Provides a fix for "ensure_image_exists" function in _**podman_container_lib.py**_ to consider tls_verify parameter when it is false.
If the parameter is not specified, it doesn't affect the execution (it is enabled by default in podman image pull command).
Fixes #810

fix for tls_verify being ignored

---

plugins/modules/podman_save.py
tests/integration/targets/podman_save/tasks/main.yml

Saved images are always changed (checksum varies) when forced (i.e. removed then re-saved). Test case added.
Fixes #826

fix(podman_save): always changed when force

---

plugins/module_utils/podman/quadlet.py

Adjust quadlet parameters to set rootfs as image and clear image field when rootfs container is being used.
e.g.:
```
containers.podman.podman_container:
rootfs: true
image: "/opt/container-root"
```
should put into a quadlet file (note, no `Image=` in a file):
```
Rootfs=/opt/container-root
```

Fix quadlet parameters when container uses rootfs

---

plugins/module_utils/podman/quadlet.py

The group_add parameter is not propagated to the container file at the moment.
This pull request adds the feature.

Add group_add parameter for podman quadlet

---

plugins/modules/podman_image.py

Skip empty volume items with `podman image build`:
```yaml
- containers.podman.podman_image:
name: myimage
path: /tmp/myimage
build:
volume:
- "{{ '/tmp/whatever:/mnt/whatever' if false }}" # results in "" (empty string), which leads to podman error
state: build
```
This PR adds a check in `podman_image` module, just like it is already done over here: https://github.com/containers/ansible-podman-collections/blob/master/plugins/module_utils/podman/podman_container_lib.py#L859-L863

fix(podman_image): skip empty volume items

---

plugins/modules/podman_image.py
tests/integration/targets/podman_image/tasks/main.yml

Fixes https://github.com/containers/ansible-podman-collections/issues/646

Trigger a new image build when we detect that the Containerfile has changed.

---

plugins/modules/podman_container.py

The underlying code has sane defaults and will figure out the directory on its own in most cases
https://github.com/containers/ansible-podman-collections/blob/0b773e5d61d1f0c8ea33b8f42dafe2267ee8e487/plugins/module_utils/podman/quadlet.py#L688-L693

don't document quadlet_dir as required when setting state=quadlet

---

plugins/modules/podman_network.py

Add new options for podman_network

---

plugins/module_utils/podman/quadlet.py
tests/integration/targets/podman_container/tasks/main.yml

As noticed in #844 the group_add parameter should be mapped to GroupAdd in the .container file.
I noticed that several other parameters are missing or not mapped correctly.
Missing parameters that should be mapped (podman version that introduced them):
Parameters that should be mapped to .container file syntax
Parameters that should be mapped to podman\_args:
There are also available parameters that can not be set using the collection but might be useful.
They are out of scope for this pull request, but some would be really useful such as AutoUpdate.
Here is a list for documentation:
- Autoupdate
- Mask
- SeccompProfile
- SecurityLabelDisable
- SecurityLabelFileType
- SecurityLabelLevel
- SecurityLabelNested
- SecurityLabelType
- Unmask
Resolves #844
This reverts commit …

Add missing parameters for podman container quadlet

---

plugins/modules/podman_login.py
tests/integration/targets/podman_login/tasks/main.yml

Add option to podman_login module to use secret on podman >= 4.7.0

Add secret to login

---

plugins/modules/podman_login.py

The podman_login module does not have code to support check runs. 
Therefore a check run in ansible does the actual login. 
Set supports_check_mode to False so the login is skipped in a dry-run.

podman_login does not support check_mode

---

plugins/module_utils/podman/quadlet.py

Fix #866 
This typo prevents the quadlet generator from picking up --cpus and --platform options.

Fix typo in quadlet generator

---

plugins/module_utils/podman/quadlet.py

cmd_args type is `list / elements=string`
, should use add operator not append

fix: quadlet cmd_args append mistake

---

plugins/modules/podman_search.py
tests/integration/targets/podman_search/tasks/main.yml

Fix list tags failure in podman_search

---

plugins/modules/podman_container_copy.py

The podman_container_copy examples use the podman_search module

Fix podman_container_copy examples

---

plugins/modules/podman_image.py

The usedforsecurity keyword argument of the hashlib functions was introduced in python 3.9. To achieve compatibility with versions below that, we only use it once it is available.
The usedforsecurity argument forces use of secure hash functions in specially compiled versions of python. In this case it would force to upgrade sha256 to a different hash function should sha256 be deemeed insecure in the future. The podman hash we are comparing against is (currently) always sha256.
As sha256 is still considered secure, removing this option for older python versions should be acceptable.
Related Issues: #902

Use usedforsecurity for hashlib.sha256 only in python version >=3.9

---

plugins/modules/podman_container.py

For quadlets you can set sdnotify (which maps to Notify=) to healthy to use a healthcheck to determine when the container is up.

Document that sdnotify can be set to healthy
