COPYING

As we got confirmations from all contributors to podman modules, we re-license it to Apache 2

Fix license text

---

plugins/modules/podman_container.py

Add podman_container module from TripleO

---

plugins/modules/podman_network_info.py

Add podman_network_info module

---

tests/integration/targets/podman_container/aliases
tests/integration/targets/podman_container/meta/main.yml
tests/integration/targets/podman_container/tasks/main.yml
tests/integration/targets/podman_network_info/aliases
tests/integration/targets/podman_network_info/meta/main.yml
tests/integration/targets/podman_network_info/tasks/main.yml

Add tests for podman_container and podman_network_info

---

galaxy.yml

Publish new collection with new modules

Update galaxy version and galaxy.yml

---

.github/workflows/collection-continuous-integration.yml
plugins/modules/podman_container.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt
tests/sanity/requirements.txt
tests/unit/requirements.txt

Add sanity tests for current modules, except of podman_container which requires specific changes.
Add building collection jobs.

Github workflow

---

.github/workflows/collection-continuous-integration.yml
tests/sanity/ignore-2.10.txt

Remove non existing unit tests jobs, create only one build job, optimize sanity.

Optimize CI

---

.github/ISSUE_TEMPLATE.md

Add issues template for bugs and features

Add issue template for github repo

---

ci/playbooks/build.yml
ci/playbooks/connection_test.yml
ci/playbooks/pre.yml
ci/run_connection_test.sh

Add support for local testing of CI and tests on Ubuntu

Improve local testing

---

.github/workflows/connections_tests.yml
.github/workflows/podman_container.yml
ci/playbooks/containers/podman_container.yml
ci/playbooks/containers_test.yml
ci/run_containers_tests.sh
contrib/README.md
galaxy.yml
plugins/modules/podman_container.py
tests/integration/targets/podman_container/aliases
tests/integration/targets/podman_container/meta/main.yml
tests/integration/targets/podman_container/tasks/main.yml
tests/integration/targets/podman_container_info/tasks/main.yml
tests/integration/targets/podman_image/tasks/main.yml
tests/integration/targets/podman_image_info/tasks/main.yml
tests/integration/targets/podman_network_info/tasks/main.yml
tests/integration/targets/podman_volume_info/tasks/main.yml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt

Add scripts and README for local executions and tests
Improve idempotency for podman_container with cgroup_parent for latest versions of podman
Run podman_container tests on changes

Set up base CI for podman container module

---

.github/workflows/podman_image.yml
ci/playbooks/containers/podman_image.yml
tests/integration/targets/podman_image/aliases
tests/integration/targets/podman_image/meta/main.yml
tests/integration/targets/podman_image/tasks/main.yml

Add CI tests for podman_image module

Add CI for podman_image

---

.github/workflows/podman_container_info.yml
.github/workflows/podman_image_info.yml
.github/workflows/podman_volume_info.yml
ci/playbooks/containers/podman_container_info.yml
ci/playbooks/containers/podman_image_info.yml
ci/playbooks/containers/podman_volume_info.yml
tests/integration/targets/podman_container_info/aliases
tests/integration/targets/podman_container_info/meta/main.yml
tests/integration/targets/podman_container_info/tasks/main.yml
tests/integration/targets/podman_image_info/aliases
tests/integration/targets/podman_image_info/meta/main.yml
tests/integration/targets/podman_image_info/tasks/main.yml
tests/integration/targets/podman_network_info/aliases
tests/integration/targets/podman_network_info/meta/main.yml
tests/integration/targets/podman_volume_info/aliases
tests/integration/targets/podman_volume_info/meta/main.yml
tests/integration/targets/podman_volume_info/tasks/main.yml

Add CI tests for podman_image, podman_image_info, podman_volume_info, podman_container_info modules

Add CI for podman_image, podman_image_info, podman_volume_info, podman_container_info

---

.github/workflows/podman_network_info.yml
ci/playbooks/containers/podman_network_info.yml
tests/integration/targets/podman_network_info/tasks/main.yml

Add checks for CI of podman_network_info module

Add CI for podman_network_info module

---

plugins/modules/podman_container.py

Fix healthcheck and --rm commands.
Fix idempotency for images.
Fix possible problem with volumesfrom not in the inspection.
Partially solves #21

Fix image, healthcheck and other idempotency

---

plugins/modules/podman_container.py
plugins/modules/podman_network_info.py

Fix #39 
Inspect image for getting preconfigured parameters like `User`, `Workdir`, etc.
Compare them if any of them is configured in the image.

Inspect image for better idempotency

---

plugins/modules/podman_image.py

Fixes #50
Add option for not verifying host.

Add option for tls_verify=false for images

---

.github/workflows/collection-continuous-integration.yml
.github/workflows/connections_tests.yml
.github/workflows/podman_container.yml
.github/workflows/podman_container_info.yml
.github/workflows/podman_image.yml
.github/workflows/podman_image_info.yml
.github/workflows/podman_network_info.yml
.github/workflows/podman_volume_info.yml

This reverts commit ce0b45a1c427e93e9ff1a098d5d4b5d3fd389951.

Revert "Hold on jobs"

---

plugins/modules/podman_container.py
tests/integration/targets/podman_container/files/Dockerfile
tests/integration/targets/podman_container/tasks/idem_volumes.yml

Add check for local volumes and detect them in module arguments.
Fixes #39

Add idempotency for existing local volumes

---

.github/workflows/collection-continuous-integration.yml
COPYING
README.md
galaxy.yml
plugins/module_utils/podman/common.py
plugins/modules/podman_container.py
plugins/modules/podman_container_info.py
plugins/modules/podman_image.py
plugins/modules/podman_image_info.py
plugins/modules/podman_network_info.py
plugins/modules/podman_volume_info.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt
tests/unit/requirements.txt

Remove ansible-metadata and redundant requirements file
Set license for GPL-v3

Relicense and clean up modules according to last Ansible changes

---

.github/workflows/collection-publish.yml
contrib/build.py
contrib/publish-requirements.txt
contrib/publish.sh
galaxy.yml.in

Publishing job for collection

---

plugins/modules/podman_container.py
tests/integration/targets/podman_container_idempotency/tasks/main.yml
tests/integration/targets/podman_container_idempotency/tasks/root-podman.yml

Fix #61 
Add ulimits checking and idempotency as best effort.

Add idempotency for ulimits and tests

---

plugins/modules/podman_container.py

In podman 2.0.0 were introduced changes in inspection of container.
Support all idempotency changes from version 2.
Fix #65

Fix idempotency for podman > 2 versions

---

plugins/modules/podman_container.py
plugins/modules/podman_container_info.py
plugins/modules/podman_image.py
plugins/modules/podman_image_info.py
plugins/modules/podman_network_info.py
plugins/modules/podman_volume_info.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
- Bugfix Pull Request
plugins/modules/podman_container.py
plugins/modules/podman_container_info.py
plugins/modules/podman_image.py
plugins/modules/podman_image_info.py
plugins/modules/podman_network_info.py
plugins/modules/podman_volume_info.py
tests/sanity/ignore-2.9.txt

sanity: doc fixes

---

.github/workflows/collection-continuous-integration.yml
.github/workflows/connections_tests.yml
.github/workflows/podman_container.yml
.github/workflows/podman_container_idem.yml
.github/workflows/podman_container_info.yml
.github/workflows/podman_image.yml
.github/workflows/podman_image_info.yml
.github/workflows/podman_network_info.yml
.github/workflows/podman_volume_info.yml
ci/run_connection_test.sh
ci/run_containers_tests.sh
plugins/modules/podman_container.py
plugins/modules/podman_image.py
tests/integration/targets/podman_container_idempotency/files/Dockerfile
tests/integration/targets/podman_container_idempotency/tasks/build_test_container.yml
tests/integration/targets/podman_container_idempotency/tasks/root-podman.yml

Fix #68 
Fix #69 
Should help to #80 as well, but will be handled separately.

Add ubuntu 20.04 to CI

---

.github/workflows/podman_pod.yml
.github/workflows/podman_pod_info.yml
ci/playbooks/containers/podman_pod.yml
ci/playbooks/containers/podman_pod_info.yml
ci/playbooks/pre.yml
plugins/modules/podman_pod.py
plugins/modules/podman_pod_info.py
tests/integration/targets/podman_pod/tasks/main.yml
tests/integration/targets/podman_pod/tasks/net-pod.yml
tests/integration/targets/podman_pod/tasks/network-tests.yml
tests/integration/targets/podman_pod/tasks/root-pod.yml
tests/integration/targets/podman_pod_info/tasks/main.yml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Fix #51 
Create modules for pods management and pod information gathering: podman_pod and podman_pod_info.

Add podman pod modules for pods management.

---

plugins/modules/podman_container.py
tests/integration/targets/podman_container_idempotency/tasks/idem_networks.yml
tests/integration/targets/podman_container_idempotency/tasks/main.yml
tests/integration/targets/podman_container_idempotency/tasks/root-podman-network.yml
tests/integration/targets/podman_container_idempotency/tasks/rootless-podman-network.yml

Fix #80 
Add network idempotency compatible with podman v1 and v2.

Fix idempotency for networks and add tests

---

.github/workflows/podman_volume.yml
ci/playbooks/containers/podman_volume.yml
plugins/modules/podman_volume.py
tests/integration/targets/podman_volume/tasks/main.yml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Fix #86 
Create podman module for volumes management

Create podman_volume module for volumes management

---

plugins/modules/podman_container.py
tests/integration/targets/podman_container/tasks/main.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_all.yml
tests/integration/targets/podman_container_idempotency/tasks/main.yml

Fix idempotency for case with = in env

---

plugins/modules/podman_container.py
tests/integration/targets/podman_container_idempotency/tasks/idem_pods.yml
tests/integration/targets/podman_container_idempotency/tasks/main.yml

Fix issue with idempotency uts, ipc with pod

---

.github/workflows/podman_container.yml
setup.cfg
setup.py

Add files to make install with pip possible: "pip install ."

Add setup files for Pip installation

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/config.yaml

Fix #99 
Add changelog for the collection.

Add changelog for Ansible 2.10 release

---

plugins/modules/podman_volume.py
tests/integration/targets/podman_volume/tasks/main.yml

Replace 'containers' by 'volume'

Fix return data from podman_volume module

---

.github/workflows/podman_network.yml
changelogs/changelog.yaml
ci/playbooks/containers/podman_network.yml
plugins/modules/podman_network.py
tests/integration/targets/podman_network/tasks/main.yml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Add podman_network module

---

plugins/module_utils/podman/common.py
plugins/modules/podman_container.py
plugins/modules/podman_network.py
plugins/modules/podman_pod.py
plugins/modules/podman_volume.py

fix diff calculation

---

plugins/modules/podman_container.py

Add note about containerPort setting in docs

---

plugins/modules/podman_container.py

Add strict image compare with hashes

---

plugins/modules/podman_logout.py

This is following up on the discussion in #134 
I've explained in the description in two places what is happening (here describing the new `ignore_docker_credentials` flag):
Credentials created using other tools such as `docker login` are not 
removed unless the corresponding `authfile` is explicitly specified.
Since podman also uses existing credentials in these files by default
(for docker e.g. `${HOME}/.docker/config.json`), module execution will
fail if a docker login exists for the registry specified in any
`authfile` is used by podman. This can be ignored by setting
`ignore_docker_credentials` to `yes`: the credentials will be kept and
`changed` will be false.
This option cannot be used together with `all` since in this case
podman will not check for existing `authfiles` created by …

Handle podman logout not logging out when logged in via different tool

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py
tests/integration/targets/podman_container_idempotency/tasks/root-podman.yml

* extended description of podman_container
* add mac_address field and add_param function in podman_container_lib
* closes #146

Add mac_address field to podman_container module

---

plugins/modules/podman_volume.py
tests/integration/targets/podman_volume/tasks/main.yml

Fix #150
Add special treat for volume GIDs and UIDs options.

Fix idempotency for volume GID and UID

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py
tests/integration/targets/podman_container_idempotency/tasks/idem_all.yml

Convert log-opts to dictionary, gidmap to list and idempotent

---

plugins/module_utils/podman/podman_container_lib.py

Handle slash removals for root volumes mount

---

plugins/modules/podman_image.py
tests/integration/targets/podman_image/tasks/main.yml

Add debug log and podman_actions to podman_image

---

plugins/modules/podman_image.py

Don't set default for validate-certs in podman_image

---

plugins/modules/podman_volume.py
tests/integration/targets/podman_volume/tasks/main.yml
tests/integration/targets/podman_volume_info/tasks/main.yml

And prepare volume tasks for versioned checks
Fix #179

Fix uid/gid checks for podman 1.6.4 volumes

---

plugins/module_utils/podman/podman_container_lib.py

Change default log level for 3+ versions

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py

And set it to lower to workaround bugs in 3.0.1
Fix #185

Convert systemd option to a string

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container_idempotency/tasks/rootless-podman-network.yml

Fix slirp4netns options idempotency

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py

Don't recreate container if env_file is specified

---

plugins/modules/podman_image.py

Don't calculate image digest in check mode

---

plugins/module_utils/podman/podman_pod_lib.py
tests/integration/targets/podman_pod/tasks/main.yml

Add support for Podman Pod restart

---

plugins/modules/podman_network.py
tests/integration/targets/podman_network/tasks/main.yml

Rootless network will always have DNS enabled.
Fix #212

Fix idempotency for rootless networks from v3

---

plugins/modules/podman_network.py
tests/integration/targets/podman_network/tasks/main.yml

Convert IPv6 to shorten form

---

plugins/modules/podman_image_info.py
tests/integration/targets/podman_image_info/tasks/main.yml

Fix error with images info where no images

---

plugins/modules/podman_login.py
tests/integration/targets/podman_login/tasks/main.yml

This is my first attempt at an Ansible module.  I have a workflow that could use a podman login task, so I thought I would give this a try.  Let me know if there is anything I missed or need to improve upon.

Podman login module

---

.github/workflows/podman_login.yml
ci/playbooks/containers/podman_login.yml
tests/integration/targets/podman_login/tasks/main.yml

Add CI for podman_login module

---

plugins/modules/podman_network.py

Pass boolean to ipv6 option in command line.
Fix #249

Fix ipv6=false issue

---

.github/workflows/podman_play.yml
ci/playbooks/containers/podman_play.yml
plugins/modules/podman_play.py
tests/integration/targets/podman_play/tasks/files/envdata.yaml
tests/integration/targets/podman_play/tasks/files/play-root1.yaml
tests/integration/targets/podman_play/tasks/files/play-root3.yaml
tests/integration/targets/podman_play/tasks/files/play1.yaml
tests/integration/targets/podman_play/tasks/files/play3.yaml
tests/integration/targets/podman_play/tasks/main.yml
tests/integration/targets/podman_play/tasks/root-play.yml

Create a module which plays Kubernetes files with Podman.
Fix #98

Add Podman play kube module

---

plugins/modules/podman_container_info.py

Workaround issue https://github.com/containers/podman/issues/10225
Add retries and pause for "podman ps"

Fix failure when listing containers

---

plugins/connection/podman.py

Fixes: https://github.com/ansible-community/molecule-podman/issues/2

Avoid exposing pipelining support for podman connections

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py
plugins/modules/podman_secret.py
tests/integration/targets/podman_secret/tasks/main.yml

Add initial secrets support

---

contrib/ansible-lint.sh
plugins/module_utils/podman/podman_pod_lib.py
plugins/modules/podman_containers.py

Add local script for running and testing with ansible-test

Fix modules for newest pylint in ansible-test

---

.github/workflows/podman_secret.yml
ci/playbooks/containers/podman_secret.yml
tests/integration/targets/podman_secret/tasks/main.yml

Run tests with podman secret

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container_idempotency/tasks/rootless-podman-network.yml

Fix idempotency when containers has a common network

Fix idempotency issues

---

plugins/module_utils/podman/podman_pod_lib.py
plugins/modules/podman_pod.py

Add support for podman pod create --infra-name

---

.github/workflows/podman_save.yml
ci/playbooks/containers/podman_save.yml
plugins/modules/podman_save.py
tests/integration/targets/podman_save/tasks/main.yml

Add podman module which saves image to disk.
Related #205

Podman save module

---

plugins/modules/podman_load.py
plugins/modules/podman_save.py

To be compatible with docker_image_load module add 'path' options
as aliases.

Add aliases for image load/save

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py
tests/integration/targets/podman_container_idempotency/tasks/idem_network_aliases.yml
tests/integration/targets/podman_container_idempotency/tasks/main.yml
tests/integration/targets/podman_container_idempotency/tasks/root-podman-network.yml
tests/integration/targets/podman_container_idempotency/tasks/root-podman.yml

Add support for network-alias flag

---

.github/ISSUE_TEMPLATE.md

Signed-off-by: Maxwell G <gotmax@e.email>

[Issue template] Use yaml syntax highlighting where appropriate

---

plugins/modules/podman_login.py

Handle tlsverify correctly in podman_login

---

plugins/modules/podman_container.py
tests/integration/targets/podman_secret/tasks/main.yml

Update secrets description and add test with secret opts

---

plugins/module_utils/podman/podman_pod_lib.py
plugins/modules/podman_pod.py

Fix #360 
Add new multiple options for Podman pods.

Add new options for pod module

---

plugins/module_utils/podman/podman_container_lib.py

Fix MAC address detection in created container

---

tests/integration/targets/podman_container/tasks/main.yml

Fix CI for podman container tests

---

plugins/module_utils/podman/podman_container_lib.py

Fix error with exitcommand for Podman v4

---

plugins/modules/podman_network.py

fix(network) fix issue when missing plugins entry

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py
tests/integration/targets/podman_image/tasks/main.yml

Fix podman collection for Podman version 4

---

CHANGELOG.rst
changelogs/changelog.yaml
docs/buildah_connection.html
docs/index.html
docs/podman_connection.html
docs/podman_container_info_module.html
docs/podman_container_module.html
docs/podman_containers_module.html
docs/podman_export_module.html
docs/podman_image_info_module.html
docs/podman_image_module.html
docs/podman_import_module.html
docs/podman_load_module.html
docs/podman_login_info_module.html
docs/podman_login_module.html
docs/podman_logout_module.html
docs/podman_network_info_module.html
docs/podman_network_module.html
docs/podman_play_module.html
docs/podman_pod_info_module.html
docs/podman_pod_module.html
docs/podman_save_module.html
docs/podman_secret_module.html
docs/podman_tag_module.html
docs/podman_volume_info_module.html
docs/podman_volume_module.html
galaxy.yml

Release 1.9.3 version

---

plugins/module_utils/podman/podman_pod_lib.py
plugins/modules/podman_pod.py
tests/integration/targets/podman_pod/tasks/net-pod.yml
tests/integration/targets/podman_pod/tasks/root-pod.yml

 Change network attribute from str to list in pods #414 #416 

---

plugins/modules/podman_login.py

Fixes #426 
This is an attempt to ensure idem-potency for the login module. I decided to calculate a hash of the auth JSON to figure out if there's been a change since the login command writes the login information to this file even if it's reusing existing credentials. An alternative could be to open the auth file and base64-encoding the provided login information to check for differences. However, I don't think that would simplify the code.

Fix idem-potency for podman_login

---

.github/workflows/collection-continuous-integration.yml
.github/workflows/collection-publish-dry-run.yml
.github/workflows/collection-publish.yml
.github/workflows/connections_tests.yml
.github/workflows/podman_container.yml
.github/workflows/podman_containers.yml

Use 2.13 Ansible version in CI jobs instead of 2.11

Use 2.13 Ansible version in CI jobs instead of 2.11

---

CHANGELOG.rst
changelogs/changelog.yaml
galaxy.yml

Release 1.9.4 version

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py

Add --sdnotify option for container

---

.github/FUNDING.yml

Create a sponsorship file

---

plugins/modules/podman_network.py
tests/integration/targets/podman_network/tasks/main.yml

Improve networks idempotency for v4

---

plugins/module_utils/podman/podman_container_lib.py

Support passing multiple networks with params

---

tests/integration/targets/podman_container/tasks/main.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_all.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_labels.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_network_aliases.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_networks.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_pods.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_ports.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_stopsignal.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_users.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_volumes.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_workdir.yml
tests/integration/targets/podman_container_idempotency/tasks/root-podman-network.yml
tests/integration/targets/podman_container_idempotency/tasks/root-podman.yml
tests/integration/targets/podman_container_idempotency/tasks/rootless-podman-network.yml
tests/integration/targets/podman_container_info/tasks/main.yml
tests/integration/targets/podman_containers/tasks/main.yml
tests/integration/targets/podman_containers/tasks/root-multi.yml
tests/integration/targets/podman_export/tasks/main.yml
tests/integration/targets/podman_import/tasks/main.yml
tests/integration/targets/podman_pod/tasks/main.yml
tests/integration/targets/podman_secret/tasks/main.yml

Prepare tests to use custom executable, part 1

---

tests/integration/targets/podman_containers/tasks/main.yml
tests/integration/targets/podman_export/tasks/main.yml
tests/integration/targets/podman_image/tasks/main.yml
tests/integration/targets/podman_image_info/tasks/main.yml
tests/integration/targets/podman_import/tasks/main.yml
tests/integration/targets/podman_load/tasks/main.yml
tests/integration/targets/podman_login/tasks/main.yml
tests/integration/targets/podman_login_info/tasks/main.yml
tests/integration/targets/podman_logout/tasks/main.yml
tests/integration/targets/podman_network/tasks/main.yml
tests/integration/targets/podman_network_info/tasks/main.yml
tests/integration/targets/podman_save/tasks/main.yml
tests/integration/targets/podman_secret/tasks/main.yml
tests/integration/targets/podman_tag/tasks/main.yml
tests/integration/targets/podman_volume/tasks/main.yml
tests/integration/targets/podman_volume_info/tasks/main.yml

Prepare tests to use custom executable, part 2

---

tests/integration/targets/podman_containers/tasks/main.yml
tests/integration/targets/podman_containers/tasks/root-multi.yml

Prepare tests to use custom executable, part 3

---

tests/integration/targets/podman_play/tasks/main.yml
tests/integration/targets/podman_play/tasks/root-play.yml
tests/integration/targets/podman_pod/tasks/main.yml
tests/integration/targets/podman_pod/tasks/net-pod.yml
tests/integration/targets/podman_pod/tasks/network-tests.yml
tests/integration/targets/podman_pod/tasks/root-pod.yml
tests/integration/targets/podman_pod_info/tasks/main.yml

Prepare tests to use custom executable, part 4

---

tests/integration/targets/podman_container/tasks/main.yml
tests/integration/targets/podman_container_idempotency/tasks/build_test_container.yml
tests/integration/targets/podman_container_idempotency/tasks/idem_pods.yml
tests/integration/targets/podman_export/tasks/main.yml
tests/integration/targets/podman_pod/tasks/net-pod.yml
tests/integration/targets/podman_pod_info/tasks/main.yml
tests/integration/targets/podman_volume/tasks/main.yml

Prepare tests to use custom executable, part 5

---

ci/playbooks/connection_test.yml
ci/run_connection_test.sh

Prepare tests to use custom executable, part 6

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container_idempotency/tasks/idem_all.yml

Improve idempotency for devices mount of rootless podman

---

plugins/modules/podman_image.py
tests/integration/targets/podman_image/tasks/main.yml

- `podman_image`: correct `path` parameter description
- `podman_image`: add `file` parameter for Containerfile location
Closes https://github.com/containers/ansible-podman-collections/issues/481.
I am not sure though if the docs are regenerated automatically and if I missed something.

`podman_image`: add `file` parameter for Containerfile location

---

plugins/modules/podman_load.py

Fix podman load module for Podman 4

---

.github/workflows/unittests.yml
test-requirements.txt
tests/unit/plugins/modules/test_common.py

Add unittests for Ansible Podman modules

---

tests/unit/plugins/modules/test_container_lib.py

Add example unittest for container lib

---

plugins/connection/podman.py

This is a very naive implementation of the fix suggested on the issue #428. Please review and comment!

Warning about improperly configured remote target

---

plugins/module_utils/podman/common.py

Use expanduser for path calculation.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2133207

Fix expanduser in path for systemd generation

---

plugins/modules/podman_generate_systemd.py

feat: allow empty string for prefixes

---

plugins/modules/podman_logout.py
tests/integration/targets/podman_logout/tasks/main.yml

Fix podman logout tests for v4

---

tests/integration/targets/podman_network/tasks/main.yml

Fix network tests for Podman v4

---

.github/workflows/podman_container.yml
.github/workflows/podman_containers.yml
.github/workflows/podman_secret.yml
ci/playbooks/install_repos.yml

Prepare CI for Podman v3 backward compatibility

---

plugins/modules/podman_network.py

Add missing options to podman network

---

plugins/module_utils/podman/podman_pod_lib.py
tests/integration/targets/podman_pod/tasks/main.yml

Fix idempotency for pods with uidmap and gidmap

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container_idempotency/tasks/idem_all.yml

Add idempotency for restart-policy for containers

---

plugins/module_utils/podman/podman_container_lib.py

Fix idempotency lowercase for devices

---

plugins/module_utils/podman/common.py
plugins/modules/podman_containers.py
plugins/modules/podman_login.py
plugins/modules/podman_login_info.py
plugins/modules/podman_logout.py
plugins/modules/podman_network.py

Fix pylint issues for CI ansible-test

---

plugins/module_utils/podman/podman_pod_lib.py

Similar to #472, but for pods. there is also support there
I wasn't sure if/how to add tests there, I'd be happy to if I can get some guidance

pod: Support passing multiple networks with params

---

plugins/modules/podman_generate_systemd.py

podman_systemd: Ignore header when comparing systemd files content

---

plugins/modules/podman_login.py

This addresses two issues:
https://github.com/containers/ansible-podman-collections/issues/564
https://github.com/containers/ansible-podman-collections/issues/565

podman-login - fix FIPS md5 issue and registry requirement

---

plugins/modules/podman_container.py

Add more explanation about cmd_args command usage

---

plugins/modules/podman_image.py
tests/integration/targets/podman_image/tasks/main.yml

Support SHA256 tag for podman images

---

tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.17.txt
tests/sanity/ignore-2.18.txt

Also include same file for next 3 releases...

Fix CI for newest Ansible branch 2.16

---

plugins/modules/podman_image.py

Add stdout to podman build and push actions

---

.github/workflows/collection-continuous-integration.yml
.github/workflows/collection-publish-dry-run.yml
.github/workflows/collection-publish.yml
.github/workflows/connections_tests.yml
.github/workflows/podman_container.yml
.github/workflows/podman_containers.yml
.github/workflows/podman_secret.yml
.github/workflows/unittests.yml

Ansible to 2.15, Python to 3.9

Fix python versions for CI, drop 2.7 job

---

plugins/module_utils/podman/podman_container_lib.py

Fix idempotency for devices

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py

Fixed idempotency with cpus parameter

---

plugins/modules/podman_image.py
tests/integration/targets/podman_image/tasks/main.yml

Also return image data when pulling it.

Fix pulling short image name

---

CHANGELOG.rst
plugins/modules/podman_export.py
plugins/modules/podman_import.py
tests/integration/targets/podman_export/tasks/main.yml
tests/integration/targets/podman_import/tasks/main.yml

adding volume import and volume export to podman_import and podman_export 
Updating integration tests
Issue #609

Adding volume import and export option

---

plugins/module_utils/podman/podman_container_lib.py

Fix healthcheck issue where defined in image

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container_idempotency/tasks/idem_all.yml

Fix idempoency issue with PID of container

---

plugins/modules/podman_container.py

Add example with quotes in command to docs

---

plugins/modules/podman_image.py

Add target support for podman build image

---

plugins/module_utils/podman/common.py

Fix common file for Python 2.7

---

plugins/modules/podman_network.py

Fix network DNS enable idempotency issue

---

plugins/modules/podman_play.py
tests/integration/targets/podman_play/tasks/files/Containerfile
tests/integration/targets/podman_play/tasks/files/kube-buil-test.yaml
tests/integration/targets/podman_play/tasks/main.yml
tests/integration/targets/podman_play/tasks/play-with-build.yml

Add build and context_dir option to podman_play

---

docs/_static/sphinx_highlight.js
docs/environment_variables.html
docs/podman_container_exec_module.html
docs/podman_prune_module.html
docs/podman_runlabel_module.html

Fix the docs for new modules

---

plugins/modules/podman_save.py
tests/integration/targets/podman_save/tasks/main.yml

Fix #670
Add examples and tests.

Fix multi-image support for podman_save

---

plugins/modules/podman_volume.py

Fix volume inspection by name in podman_volume

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py
tests/integration/targets/podman_container/tasks/main.yml
tests/integration/targets/podman_containers/tasks/main.yml

Add options to different statuses like start, stop, restart etc.
Refine detach and attach logic.

Add new arguments to podman status commands

---

plugins/modules/podman_container_exec.py
tests/integration/targets/podman_container_exec/tasks/main.yml

And add "executable" parameter to be aligned with other modules Fix #711

Return data for podman exec module

---

plugins/modules/podman_image_info.py

Fix wrong return data type in podman_image_info

---

plugins/modules/podman_play.py
tests/integration/targets/podman_play/tasks/files/multi-yaml.yml
tests/integration/targets/podman_play/tasks/main.yml
tests/integration/targets/podman_play/tasks/play-multi-yaml.yml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.13.txt
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.17.txt
tests/sanity/ignore-2.18.txt
tests/sanity/ignore-2.9.txt

Add support for kube yaml files with multi-documents

---

plugins/module_utils/podman/podman_container_lib.py

Fix pasta networking idempotency for v5

---

plugins/module_utils/podman/podman_pod_lib.py
plugins/module_utils/podman/quadlet.py
plugins/modules/podman_pod.py
tests/integration/targets/podman_pod/tasks/main.yml
tests/integration/targets/podman_pod/tasks/resource-limit.yml

Add new options to pod module

---

plugins/modules/podman_image.py

Push can support more arguments, let's add extra args for it.

Add extra_args for podman_image push and pull

---

plugins/modules/podman_image.py

Fix transports issues in podman_image

---

plugins/modules/podman_image.py

This reverts commit 7ad3dc53d5dce9f905a0228ad4128cf489bea4e6.
It requires more work

Revert "Fix transports issues in podman_image (#619)"

---

plugins/modules/podman_network.py
tests/integration/targets/podman_network/tasks/main.yml

Add route, dns and ipam_driver to podman_network

---

plugins/modules/podman_volume.py
tests/integration/targets/podman_volume/tasks/main.yml

Add mount and unmount for volumes

---

plugins/modules/podman_secret.py
tests/integration/targets/podman_secret/tasks/main.yml

Add path and env options for podman_secret

---

plugins/module_utils/podman/podman_container_lib.py

Fix idempotency for systemd generations

---

plugins/module_utils/podman/podman_pod_lib.py

Fix idempotency for pods in case of systemd generation

---

plugins/module_utils/podman/quadlet.py

The code should be setting `--exit-policy` to the value of `params['exit_policy']` instead of `params['gpus']`

params gpus should be exit_policy

---

plugins/module_utils/podman/common.py
tests/integration/targets/podman_container_idempotency/tasks/idem_all.yml

Fix idempotency for empty values

---

plugins/module_utils/podman/common.py
plugins/module_utils/podman/podman_container_lib.py
plugins/module_utils/podman/quadlet.py
tests/integration/targets/podman_container_idempotency/tasks/idem_all.yml

Idempotency improvements

---

plugins/module_utils/podman/podman_container_lib.py
plugins/module_utils/podman/quadlet.py

Fix quadlet parameters for restart policy

---

plugins/modules/podman_image.py

Add arch to podman build command explicitly

---

plugins/module_utils/podman/quadlet.py

Add support for check_mode in Quadlet

---

plugins/module_utils/podman/podman_container_lib.py

Disable idempotency for pod_id_file

---

plugins/modules/podman_image.py

Fix logic in Podman images

---

plugins/module_utils/podman/podman_container_lib.py

Fix command idempotency with quotes

---

docs/podman_image_module.html
plugins/modules/podman_image.py

Updating documentation and the error related to setting destination in the podman_image task to be in line with new functionality.
Discussion here: https://github.com/containers/ansible-podman-collections/issues/830

Update error and docs for new dest functionality in podman image

---

plugins/module_utils/podman/common.py

Fix max_size idempotency issue

---

plugins/modules/podman_container.py

Fixes https://github.com/containers/ansible-podman-collections/issues/861

Fix unsupported pull policy in example on podman_container.py

---

plugins/module_utils/podman/podman_container_lib.py
plugins/module_utils/podman/podman_pod_lib.py
plugins/module_utils/podman/quadlet.py
plugins/modules/podman_container.py
plugins/modules/podman_image.py
plugins/modules/podman_network.py
plugins/modules/podman_play.py
plugins/modules/podman_pod.py
plugins/modules/podman_volume.py
tests/integration/targets/podman_container/tasks/main.yml
tests/integration/targets/podman_image/tasks/main.yml
tests/integration/targets/podman_network/tasks/main.yml
tests/integration/targets/podman_play/tasks/main.yml
tests/integration/targets/podman_pod/tasks/main.yml
tests/integration/targets/podman_volume/tasks/main.yml

Add quadlet file mode option to specify file permission

---

plugins/module_utils/podman/podman_container_lib.py

Don't check image availability in Quadlet

---

plugins/modules/podman_container.py

docs(podman_container): improve comments on network property

---

plugins/module_utils/podman/podman_container_lib.py
plugins/modules/podman_container.py
tests/integration/targets/podman_containers/tasks/main.yml

Convert DNS domain search to a list

---

plugins/module_utils/podman/common.py

Fixes https://github.com/containers/ansible-podman-collections/issues/892, a regression introduced in https://github.com/containers/ansible-podman-collections/pull/862.

Fix idempotency for containers with env vars containing MAX_SIZE

---

plugins/module_utils/podman/podman_container_lib.py

Remove docker protocol when inspecting image

---

plugins/module_utils/podman/quadlet.py
tests/integration/targets/podman_container/tasks/main.yml

correctly quote labels and environment variables for quadlets

---

setup.cfg

Fix setuptools

---

plugins/module_utils/podman/podman_container_lib.py

Handle image arguments in podman_container

---

plugins/module_utils/podman/quadlet.py

Fix None values in LogOpt in Quadlet

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container_idempotency/tasks/idem_all.yml

Fix idempotency for systemd keyword

---

plugins/module_utils/podman/podman_container_lib.py
tests/integration/targets/podman_container_idempotency/tasks/idem_volumes.yml

Changed the diffparam_volume function to include the volume mount opts.
Fix: #940

podman_container_lib: Added checks for volume opts

---

CONTRIBUTING.md
README.md
contrib/ansible-unit.sh

Improve docs and guides

---

.github/workflows/podman_image.yml
.github/workflows/reusable-module-test.yml
plugins/module_utils/podman/podman_image_lib.py
plugins/modules/podman_image.py
tests/integration/targets/podman_image/tasks/additional_tests.yml
tests/integration/targets/podman_image/tasks/scp.yml

Add podman image scp option

---

.github/workflows/podman_system_connection.yml
.github/workflows/podman_system_connection_info.yml
ci/playbooks/containers/podman_system_connection.yml
ci/playbooks/containers/podman_system_connection_info.yml
plugins/modules/podman_system_connection.py
plugins/modules/podman_system_connection_info.py
tests/integration/targets/podman_system_connection/tasks/main.yml
tests/integration/targets/podman_system_connection_info/tasks/main.yml

Add podman system connection modules

---

plugins/module_utils/podman/common.py
plugins/modules/podman_container_exec.py

Fix Ansible sanity issues for new version

---

.github/workflows/build_latest_podman.yml

Bump Go version for building Podman

---

plugins/modules/podman_tag.py
tests/integration/targets/podman_tag/tasks/main.yml
tests/unit/plugins/modules/test_podman_tag.py

- [ X] Bug fix (non-breaking change which fixes an issue)
This fixes idempotency of podman_tag
Fixes issue #934
- [ X] Unit tests
- [ X] Integration tests
- [X ] I have performed a self-review of my own code
- [X ] I have added tests that prove my fix is effective or that my feature works
Assisted by ChatGPT

Fix idempotency for tagging local images
